### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by alpacq** [MrBuddyCasino/mcp9808-rs#1]
Hi,
I tried to use your MCP9808 crate and the embedded_hal dependency you have is 0.1.3 and causes error when building application with current version (0.2.7). Is there any way you could try to fix this?

**Comment by MrBuddyCasino** [comment]
Feel free to update the dependency and submit a PR! Its been a while since I touched that code. :)

**Comment by alpacq** [comment]
I cannot push my changes :(
Switched to a new branch 'feature/update_to_current_embedded_hal'
16:46:24.483: [mcp9808-rs] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/feature/update_to_current_embedded_hal:refs/heads/feature/update_to_current_embedded_hal --set-upstream
remote: Permission to MrBuddyCasino/mcp9808-rs.git denied to alpacq.
fatal: unable to access 'https://github.com/MrBuddyCasino/mcp9808-rs.git/': The requested URL returned error: 403
16:46:28.113: [mcp9808-rs] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/feature/update_to_current_embedded_hal:refs/heads/feature/update_to_current_embedded_hal --set-upstream
remote: Permission to MrBuddyCasino/mcp9808-rs.git denied to alpacq.
fatal: unable to access 'https://github.com/MrBuddyCasino/mcp9808-rs.git/': The requested URL returned error: 403

**Comment by MrBuddyCasino** [comment]
You cannot directly push to my repository, because it is owned by me. If you are unfamiliar with how Github Pull Requests work, I believe this is the relevant documentation: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by MrBuddyCasino** [comment]
@alpacq issue should be resolved now thanks to @ShakenCodes PR
