### ISSUE TITLE
Alternative address is necessary

### ISSUE THREAD

**Issue by Joker2770** [MrBuddyCasino/mcp9808-rs#4]
There is only a default address available now. I hope to extend alternative address like this: 
https://github.com/lukwol/mcp9808/blob/2a9f95dcd7422ccb37f341b06128efa66861fd50/src/address.rs

**Comment by MrBuddyCasino** [comment]
Are you asking if you should create a PR?

**Comment by Joker2770** [comment]
> Are you asking if you should create a PR?

In fact, I am on exploring period in Rust, and not sure if could handle this problem. But I am willing to have a try.

**Comment by MrBuddyCasino** [comment]
Sorry I‘m sick rn, will take a while until I can take a proper look.

**Comment by dcampbell24** [comment]
Going to merge now?

**Comment by Joker2770** [comment]
> Going to merge now?

I had tested some cases with Multi-MCP9808, and everything seems OK. I think it is fine to merge currently.

**Comment by MrBuddyCasino** [comment]
Yeah of course, sorry - I don't have much time due to baby, looks fine just had one comment.

**Comment by MrBuddyCasino** [comment]
Merged.
